name: Deploy to Cloudflare Pages on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Node.js (jika perlu build)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3. Install dependencies & build
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # 4. Deploy hasil build ke Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages deploy ./dist \
            --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} \
            --branch releases/${{ github.event.release.tag_name }} \
            --commit-hash ${{ github.sha }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
